# Generated by Django 5.2.4 on 2025-08-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsheet',
            name='file',
            field=models.FileField(upload_to='pdf-uploads'),
        ),
    ]
