# Generated by Django 5.2.4 on 2025-08-21 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsheet',
            name='file',
            field=models.FileField(upload_to='pdf-uploads', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
