# Generated by Django 5.2.4 on 2025-08-25 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_musicsheet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsheet',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='musicsheet',
            name='file',
            field=models.FileField(upload_to='pdf-uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
