# Generated by Django 5.2.4 on 2025-08-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_musicsheet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_uploader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musicsheet',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
