# Generated by Django 5.2.4 on 2025-08-25 18:27

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_musicsheet_thumbnail_alter_musicsheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsheet',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='musicsheet',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnails/'),
        ),
    ]
