# Generated by Django 5.2.4 on 2025-08-26 11:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_musicsheet_file_alter_musicsheet_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsheet',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
