# Generated by Django 5.2.4 on 2025-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_musicsheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicsheet',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
